import{a as L,i as d}from"./assets/vendor-ByN8xaf9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function p(t,s){const o="28988b93b6304d3885e33119dfdb45e9",r="https://newsapi.org/v2/everything",n={apiKey:o,q:t,pageSize:8,page:s};return(await L.get(r,{params:n})).data}function T(t){const s="https://static6.depositphotos.com/1026266/543/i/450/depositphotos_5437053-stock-photo-woman-pressing-modern-error-button.jpg";let{autor:o,title:i,description:e,publishedAt:r,url:n,urlToImage:f=s}=t;return`
      <li class="li-elem">
    <h2 class="title-h2">${i}</h2>
    <img class="image" src="${f}" alt="">
    ${o?`<p class="autor">${o}</p>`:""}
    <p class="decr">${e}</p>
    <a class="link" href="${n}">Посилання на джерело</a>
    <p class="date"> Was posted ${new Date(r).toLocaleString()}</p>
  </li>`}function m(t){return t.map(T).join("")}const c={form:document.querySelector(".form"),btn:document.querySelector(".js-btn"),ul_list:document.querySelector(".ul-js"),loader:document.querySelector(".loader-btn")},A=8;let l,a,u;c.form.addEventListener("submit",async t=>{t.preventDefault(),l=new FormData(t.target).get("search-text"),a=1;try{const o=await p(l,a);console.log(o);const i=m(o.articles);c.ul_list.innerHTML=i,u=Math.ceil(o.totalResults/A),b(`Дані успішно завантажені!Загалом сторінок: ${u}`)}catch{y("Можлива помилка серверу");return}E(),h(),t.target.reset()});c.loader.addEventListener("click",async t=>{a+=1,g();try{const s=await p(l,a),o=m(s.articles);c.ul_list.insertAdjacentHTML("beforeend",o),b("Дані успішно завантажені!")}catch{y("Можлива помилка серверу")}h()});function E(){c.loader.classList.remove("hidden")}function g(){c.loader.disabled=!0}function N(){c.loader.disabled=!1}function h(){a>=u?(g(),w("Це остання сторінка")):N()}function y(t){d.error({title:"Щось пішло не так 😥",message:t,position:"topRight",timeout:4e3})}function b(t){d.success({title:"Успіх!😄",message:t,position:"topRight",timeout:2e3})}function w(t){d.warning({title:"УВАГА!😲",message:t,timeout:4e3})}
//# sourceMappingURL=index.js.map
